apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "terraria.name" . }}
    helm.sh/chart: {{ include "terraria.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "terraria.name"  .}}
  annotations:
  {{ toYaml .Values.terraria.service.annotations | indent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: terraria-proxy
      port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "terraria.name" . }}
    app.kubernetes.io/part-of: {{ include "terraria.name"  .}}
